# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 7afdb0da2049e9c52eb4fc4dc3ec501e40a3a08846ee6ca21618f940565fa4762288722a4bdeed402d7a1f9e8ea9880395775773815bbd4c0cfb2696f3695d83

test:
  secret_key_base: 1a0dd37c6a5de1433125772f7d07ac95ad5b596a761c71e5283af551c7b9dd9480eca8426d041a9ada6c1bc99206305dc9b1bb95d68315b7673eb31ac23bbc46

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
